version: "3"
services:
  # API用のサーバport5000がコンテナにつながる,ホストの./apiがコンテナの/apiにマウントされる
  api_service:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api/code
    env_file:
      - ./api/backend_app/.env

  # 通信用のサーバport5001がコンテナにつながる,ホストの./communicationがコンテナの/communicationにマウントされる
  communication_service:
    build:
      context: .
      dockerfile: ./communication/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./communication:/communication
      - /communication/node_modules
      - ./app:/communication/app
