version: "3"
services:
  # API用のサーバport3001がコンテナにつながる,ホストの./apiがコンテナの/apiにマウントされる
  api_service:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "sh ./start.sh"
    ports:
      - "3001:3001"
    volumes:
      - ./api:/code
      - ./bat/src:/bat/src
    env_file:
      - ./api/backend_app/.env

  # 通信用のサーバport3000がコンテナにつながる,ホストの./communicationがコンテナの/communicationにマウントされる
  communication_service:
    build:
      context: .
      dockerfile: ./communication/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./communication:/communication
      - /communication/node_modules
      - ./app:/communication/app
