version: '3'
services:
# API用のサーバport5000がコンテナにつながる,ホストの./apiがコンテナの/apiにマウントされる
  api_service:
    build:
      context: ./api/Dockerfile
      dockerfile: api_image
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    networks:
      main:
        ipv4_address: 192.168.0.1/24
# 通信用のサーバport5001がコンテナにつながる,ホストの./communicationがコンテナの/communicationにマウントされる
  communication_service:
    build:
      context: ./communication/Dockerfile
      dockerfile: communication_image
    ports:
      - "5001:5001"
    volumes:
      - ./communication:/communication
    networks:
      main:
        ipv4_address:192.168.0.2/24
  
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24


    