version: '3'
services:
  # API用のサーバport3001がコンテナにつながる,ホストの./apiがコンテナの/apiにマウントされる
  api_service:
    build:
      dockerfile: ./api/Dockerfile
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "sh ./start.sh"
    ports:
      - "3001:3001"
    volumes:
      - ./api:/code
      - ./bat/src:/bat/src
    env_file:
      - ./api/backend_app/.env

  # 通信用のサーバport3000がコンテナにつながる,ホストの./communicationがコンテナの/communicationにマウントされる
  communication_service:
    build:
      dockerfile: ./communication/Dockerfile
      context: ./communication
    ports:
      - "3000:3000"
    volumes:
      - ./communication:/communication
    networks:
      main:
        ipv4_address:192.168.0.2/24
  
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24


    