# Generated by Django 3.2.18 on 2023-06-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='AppUser',
        ),
    ]
