# Generated by Django 3.2.18 on 2023-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_favorite_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
