version: "3"
volumes:
  node_modules:
services:
  communication:
    container_name: ms-communication
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/communication
      - node_modules:/communication/node_modules
