version: "3"

services:
  # db:
  #   image: postgres
  api:
    build: .
    command: bash -c "sh ./start.sh"
    volumes:
      - .:/code
      - ../bat/src:/bat/src
    ports:
      - "8000:8000"
    env_file:
      - ./backend_app/.env
    # depends_on:
    #   - db
